import React, { useEffect, useRef, useState } from "react"

const shuffle = (array) => {
  const copy = [...array]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

function Game() {
  const numbers = Array.from({ length: 90 }, (_, i) => i + 1)

  // GAME STATE
  const [phase, setPhase] = useState("home")
  // home | waiting | selecting | running | finished

  const [inputCode, setInputCode] = useState("")
  const [gameCode, setGameCode] = useState("")

  const [timeLeft, setTimeLeft] = useState(30)

  const [drawOrder, setDrawOrder] = useState(() => shuffle(numbers))
  const [currentIndex, setCurrentIndex] = useState(-1)

  const [selectedNumbers, setSelectedNumbers] = useState([])
  const [touchedNumbers, setTouchedNumbers] = useState([])

  const selectionTimerRef = useRef(null)
  const drawTimerRef = useRef(null)

  const generatedNumbers =
    currentIndex >= 0 ? drawOrder.slice(0, currentIndex + 1) : []

  const hitCount = touchedNumbers.length
  const currentNumber =
    currentIndex >= 0 ? drawOrder[currentIndex] : null

  // -------------------------
  // RESET / HOME
  // -------------------------
  const goHome = () => {
    const ok = window.confirm("Quit game and go home?")
    if (!ok) return

    setPhase("home")
    setGameCode("")
    setInputCode("")
    setTimeLeft(30)
    setSelectedNumbers([])
    setTouchedNumbers([])
    setCurrentIndex(-1)
    setDrawOrder(shuffle(numbers))

    clearTimeout(selectionTimerRef.current)
    clearInterval(drawTimerRef.current)
  }

  // -------------------------
  // CREATE GAME
  // -------------------------
  const startGame = () => {
    const code = Math.random().toString(36).substring(2, 7).toUpperCase()
    setGameCode(code)
    setDrawOrder(shuffle(numbers))
    setPhase("waiting")
  }


  // -------------------------
  // JOIN GAME
  // -------------------------
  const joinGame = () => {
    if (!inputCode) return

    setGameCode(inputCode.toUpperCase())
    setDrawOrder(shuffle(numbers))
    setPhase("waiting")   // ✅ FIXED
  }

  // -------------------------
  // PLAY GAME
  // -------------------------
  const playGame = () => {
    setPhase("selecting")
    setTimeLeft(30)
  }

  // -------------------------
  // SELECTION TIMER
  // -------------------------
  useEffect(() => {
    if (phase !== "selecting") return

    if (timeLeft === 0) {
      autoSelect()
      startDraw()
      return
    }

    selectionTimerRef.current = setTimeout(() => {
      setTimeLeft((t) => t - 1)
    }, 1000)

    return () => clearTimeout(selectionTimerRef.current)
  }, [timeLeft, phase])

  // const autoSelect = () => {
  //   if (selectedNumbers.length < 15) {
  //     const auto = shuffle(numbers).slice(0, 15)
  //     setSelectedNumbers(auto)
  //   }
  // }
  const autoSelect = () => {
  if (selectedNumbers.length === 15) return;

  // Numbers that the user has NOT selected
  const remainingNumbers = numbers.filter(
    (num) => !selectedNumbers.includes(num)
  );

  // Shuffle the remaining numbers
  const shuffledRemaining = shuffle(remainingNumbers);

  // Generate only the required number of values
  const autoGenerated = shuffledRemaining.slice(
    0,
    15 - selectedNumbers.length
  );

  // Combine user-selected numbers with auto-generated numbers
  setSelectedNumbers([...selectedNumbers, ...autoGenerated]);
};

  // -------------------------
  // START DRAW
  // -------------------------
  const startDraw = () => {
    setPhase("running")

    drawTimerRef.current = setInterval(() => {
      setCurrentIndex((prev) => {
        if (prev >= 89) {
          clearInterval(drawTimerRef.current)
          setPhase("finished")
          return prev
        }
        return prev + 1
      })
    }, 5000)
  }

  // -------------------------
  // SELECT NUMBER
  // -------------------------
  const toggleSelect = (num) => {
    if (phase !== "selecting") return

    if (selectedNumbers.includes(num)) {
      setSelectedNumbers(selectedNumbers.filter((n) => n !== num))
    } else {
      if (selectedNumbers.length === 15) return
      setSelectedNumbers([...selectedNumbers, num])
    }
  }

  // -------------------------
  // TOUCH NUMBER
  // -------------------------
  const handleTouch = (num) => {
    if (phase !== "running") return
    if (!generatedNumbers.includes(num)) return
    if (!selectedNumbers.includes(num)) return
    if (touchedNumbers.includes(num)) return

    setTouchedNumbers([...touchedNumbers, num])
  }

  // -------------------------
  // WIN CHECK
  // -------------------------
  useEffect(() => {
    if (hitCount === 15 && phase === "running") {
      setPhase("finished")
      clearInterval(drawTimerRef.current)
    }
  }, [hitCount, phase])

   const Goto = () => {
    
    setPhase("home")
    // navigate("/")
    setGameCode("")
    setInputCode("")
    setTimeLeft(30)
    setSelectedNumbers([])
    setTouchedNumbers([])
    setCurrentIndex(-1)
    setDrawOrder(shuffle(numbers))
    
  }
  // -------------------------
  // UI
  // -------------------------
  return (
    <div className="game" style={{ fontFamily: "Arial, sans-serif" }}>

      {/* HEADER */}
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom:"15px"}}>
        <h2 style={{ color: "#1e00ff", textShadow:'1px 1px white',fontWeight:"bold", letterSpacing:"1px"}}>Housie Game</h2>
        {phase !== "home" && (
          <button onClick={goHome} style={{ background: "red", marginRight:"5px", color: "#000000",fontWeight: "bold", padding: "5px 10px", border: "none", borderRadius: "5px", cursor: "pointer" }}>
            Quit
          </button>
        )}
      </div>

      {/* ---------------- HOME ---------------- */}
      {phase === "home" && (
        <div style={{ display: "flex", alignItems: "center", marginBottom: "10px" , justifyContent: "space-between"}}>
          {/* <button style={{fontSize: "18px", padding: "5px 15px", border: "1px solid #2d2a2a", borderRadius: "7px", cursor: "pointer"}} onClick={startGame}>Start Game</button> */}
          <button className="primary-btn" onClick={startGame}>Start Game</button>
       
        <div style={{ display: "flex", alignItems: "center", marginRight: "2%"}}>

          <input
            type="text"
            style={{ padding: "5px 7px",fontSize: "18px",border: "1px solid #2d2a2a", marginRight: "0px", borderTopLeftRadius: "7px", borderBottomLeftRadius: "7px" }}
            placeholder="Enter Team Code"
            value={inputCode}
            onChange={(e) => setInputCode(e.target.value)}
          />

          <button style={{fontSize: "18px", padding: "5px 10px", border: "1px solid #2d2a2a", borderTopRightRadius: "7px", borderBottomRightRadius: "7px", cursor: "pointer"}} onClick={joinGame}>OK</button>
        </div>
        </div>
      )}

      {/* ---------------- WAITING ---------------- */}
      {phase === "waiting" && (
        <div>
          <h3 style={{ fontSize: "18px", padding: "5px 10px", paddingLeft: "0px", marginBottom: "10px" }}>Team Code : <button style={{ border: "1px solid #000000", background: "#999999a6", color: "#ffffff", padding: "3px 10px", fontSize: "16px", borderRadius: "7px", marginLeft: "10px" }}>{gameCode}</button></h3>
          <button  className='primary-btn' 
          // style={{ border: "1px solid #000000", background: "#dcdcdc8b", color: "#000000", padding: "5px 10px", cursor: "pointer", fontSize: "18px", borderRadius: "7px", cursor: "pointer" }}
           onClick={playGame}>
            Play Game
          </button>
        </div>
      )}

      {/* ---------------- SELECTING ---------------- */}
      {phase === "selecting" && (
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
          {/* <h3>TeamCode: {gameCode}</h3> */}
          <h3 style={{ fontSize: "16px", paddingLeft: "0px"}}>Team Code : <button style={{ border: "1px solid #000000", background: "#9b9b9b8b", color: "#ffffff", padding: "2px 10px", fontSize: "15px", borderRadius: "7px"}}>{gameCode}</button></h3>
          <h4 style={{ fontSize: "16px", paddingLeft: "0px"}}>Selected: {selectedNumbers.length}/15</h4>
          <h3 style={{ fontSize: "16px", paddingLeft: "0px"}}>Time Left: <button style={{ border: "1px solid #000000", background: "#a1a1a1ae", color: "#ffffff", padding: "2px 10px", fontSize: "15px", borderRadius: "7px"}}>{timeLeft}s</button></h3>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(10,1fr)", width:"100%", marginBottom: "20px" }}>
            {numbers.map((n) => (
              <button
                key={n}
                onClick={() => toggleSelect(n)}
                style={{height: "35px", fontSize: "15px", borderRadius: "1px",fontWeight:"bold",
                  margin: 0,
                  padding: 2,
                  background: selectedNumbers.includes(n) ? "blue" : "#e6e6e6",
                  color: selectedNumbers.includes(n) ? "#fff" : "#000",
                  cursor: "pointer"
                }}
              >
                {n}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ---------------- RUNNING / FINISHED ---------------- */}
      {(phase === "running" || phase === "finished") && (
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "10px"}}>
          {/* <h3>Game Code: {gameCode}</h3> */}
          <h3 style={{ fontSize: "18px", padding: "5px 10px", paddingLeft: "0px"}}>Team Code : <button style={{ border: "1px solid #000000", background: "#b5b5b58b", color: "#ffffff", padding: "3px 10px", fontSize: "17px", borderRadius: "7px", marginLeft: "10px" }}>{gameCode}</button></h3>
          <h3 style={{ fontSize: "18px", padding: "5px 10px", paddingLeft: "0px"}}>Current Number:<button style={{ border: "1px solid #666666", background: "#04ff00", color: "#000000", fontSize: "18px", borderRadius: "50%", marginLeft: "10px", height: "35px", width: "35px" }}>{currentNumber ?? "00"}</button></h3>
         </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(10,1fr)", marginBottom: "20px", width: "100%" }}>
            {numbers.map((n) => (
              <button
                key={n}
                onClick={() => handleTouch(n)}
                disabled={!generatedNumbers.includes(n)}
                style={{ height: "35px", fontSize: "15px", borderRadius: "1px",
                  margin: 0.5,
                  padding: 2,
                  cursor: "pointer",
                  background: touchedNumbers.includes(n)
                    ? "green"
                    : selectedNumbers.includes(n)
                    ? "#a0c6fb"
                    : "#d4d1d1",
                    
                }}
              >
                {n}
              </button>
            ))}
          </div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "10px", postion: "relative"}}>
          <h4 style={{background:'#16a34a', padding:'5px 20px', borderRadius:'5px'}}>Hits : {hitCount}/15</h4>
          {phase === "finished" && hitCount === 15 && (
            <button onClick={Goto} style={{ border: "1px solid #000000", background: "#2530ff", color: "#ffffff", padding: "3px 10px", fontSize: "18px", borderRadius: "7px", marginLeft: "10px", cursor: "pointer" }}>Submit</button>
          )}

          {phase === "finished" && hitCount < 15 && (
            <button onClick={Goto} style={{ border: "1px solid #000000", background: "#2a35ff", color: "#000000", padding: "3px 10px", fontSize: "18px", borderRadius: "7px", marginLeft: "10px", cursor: "pointer" }}>Accept</button>
          )}
          </div>
          <h4 className="generated-box">Generated Numbers: {generatedNumbers.join(", ")}</h4>
          
        </div>
      )}
    </div>
  )
}

export default Game