import { Link } from 'react-router-dom'

import image1 from "../assets/image1.png";
import image2 from "../assets/image2.png";


function Home() {
  return (
    <div className='home' style={{ padding: "20px" }}>
      <h1>Welcome to Housie App</h1>
      <div className='home1'>
      {/* <p>Select a menu option</p> */}
      <Link to="/game" className='home2'>
      <img
    src={image1}
    alt="Housie Hit Numbers" width="200px" heiht="200px"/>       
      <button style={{ padding: '10px 20px', marginTop: '20px', cursor: 'pointer' }}>
          Go to Housie Game
        </button>
      </Link>
      <Link to="/game1" className='home2'>
      {/* <img src={housieImg} alt="Housie Hit Numbers" className="profile-image"/> */}
      <img
    src={image2}
    alt="Auto Generated Numbers" width="200px" heiht="200px"/>
        <button style={{ padding: '10px 20px', marginTop: '20px', cursor: 'pointer' }}>
          Autogenerated
        </button>
      </Link>
      </div>
    </div>
  );
}

export default Home;