import { Link } from 'react-router-dom'

// import housieImg from "../assets/housie-hit.png";

function Home() {
  return (
    <div className='home' style={{ padding: "20px" }}>
      <h1>Welcome to Housie App</h1>
      <div className='home1'>
      {/* <p>Select a menu option</p> */}
      <Link to="/game" className='home2'>
      <img
    src="https://i.etsystatic.com/33780479/r/il/f49a8c/8204944742/il_1588xN.8204944742_epfo.jpg"
    alt="Housie Hit Numbers" width="200px" heiht="200px"/>       
      <button style={{ padding: '10px 20px', marginTop: '20px', cursor: 'pointer' }}>
          Go to Housie Game
        </button>
      </Link>
      <Link to="/game1" className='home2'>
      {/* <img src={housieImg} alt="Housie Hit Numbers" className="profile-image"/> */}
      <img
    src="https://i.etsystatic.com/21594655/r/il/31057e/6487436113/il_1588xN.6487436113_5fin.jpg"
    alt="Auto Generated Numbers" width="200px" heiht="200px"/>
        <button style={{ padding: '10px 20px', marginTop: '20px', cursor: 'pointer' }}>
          Autogenerated
        </button>
      </Link>
      </div>
    </div>
  );
}

export default Home;